{
 "title": "Marzban",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  { "title": "Stat NOW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT COUNT(id) 'Online Users', online_at FROM marzban.users where online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE) group by online_at"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT c.node,\r\n       count(a.id) 'users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT\r\n        user_id,\r\n        IFNULL(n.name, 'Main') AS node,\r\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY node_id) AS row_num\r\n    FROM node_user_usages AS a\r\n    LEFT JOIN nodes AS n ON n.id = a.node_id\r\n    WHERE DATE(a.created_at) = CURDATE()\r\n        AND HOUR(a.created_at) = HOUR(NOW())\r\n) AS c ON c.row_num = 1 AND c.user_id = a.id\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\ngroup by c.node\r\n"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "SELECT b.type 'Client',\r\n       count(a.id) 'Users'\r\nFROM users AS a\r\nLEFT JOIN (\r\n    SELECT DISTINCT \r\n           sub_last_user_agent,\r\n           CASE \r\n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \r\n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\r\n           END AS type\r\n    FROM users\r\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\r\nWHERE online_at >= DATE_SUB(NOW(), INTERVAL 1 MINUTE)\r\n\r\ngroup by b.type\r\n"
    }
   ]
  },
  {
   "title": "Online Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "Select \r\n  name\r\nfrom nodes where status in ('connected') "
    }
   ]
  },
  {
   "title": "Offline Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "Select \r\n  name\r\nfrom nodes where status in ('connecting', 'error') "
    }
   ]
  },
  { "title": "Today stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Today users",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select SUM(`a`.`used_traffic`) AS `used_traffic`,\r\n                            ifnull(`n`.`name`, 'Main') AS `node`\r\n                        from ( (\r\n                                    `node_user_usages` `a`\r\n                                    left join `users` `u` on( (`u`.`id` = `a`.`user_id`))\r\n                                )\r\n                                left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`))\r\n                            )\r\n                        where (\r\n                                `a`.`created_at` >= concat( curdate(),' 00:00:00'\r\n                                )\r\n                            )\r\n                            group by ifnull(`n`.`name`, 'Main')"
    }
   ]
  },
  {
   "title": "Traffic by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select \r\n                            ifnull(`n`.`name`, 'Main') AS `Node`,\r\n                            SUM(`a`.`used_traffic`) AS `Traffic`\r\n                        from ( (\r\n                                    `node_user_usages` `a`\r\n                                    left join `users` `u` on( (`u`.`id` = `a`.`user_id`))\r\n                                )\r\n                                left join `nodes` `n` on( (`n`.`id` = `a`.`node_id`))\r\n                            )\r\n                        where (\r\n                                `a`.`created_at` >= concat( curdate(),' 00:00:00'\r\n                                )\r\n                            )\r\n                            group by ifnull(`n`.`name`, 'Main')"
    }
   ]
  },
  {
   "title": "Traffic by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select a.created_at 'Datetime', sum(a.used_traffic) 'Traffic' from node_user_usages a\r\njoin nodes n on n.id = a.node_id\r\nwhere a.created_at >= concat( curdate(),' 00:00:00')\r\ngroup by a.created_at\r\norder by a.created_at ASC\r\n"
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "marzban",
     "rawSql": "select a.created_at 'Datetime', count(a.created_at) from node_user_usages a where a.created_at >= concat( curdate(),' 00:00:00') group by a.created_at \r\norder by a.created_at ASC"
    }
   ]
  }
 ]
}