{
 "title": "Marzban",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Online users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(id) 'Online Users' FROM users where online_at >= DATETIME('now', '-1 minute') ",
     "rawQueryText": "SELECT COUNT(id) 'Online Users' FROM users where online_at >= DATETIME('now', '-1 minute') "
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT c.node,\n       COUNT(a.id) AS 'users'\nFROM users AS a\nLEFT JOIN (\n    SELECT\n        user_id,\n        case when n.name = '' then 'Main' else IFNULL(n.name, 'Main') end AS node,\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY a.ID) AS row_num\n    FROM node_user_usages AS a\n    LEFT JOIN nodes AS n ON n.id = a.node_id\n    WHERE DATE(a.created_at) = DATE('now')\n        AND strftime('%H', a.created_at) = strftime('%H', 'now')\n) AS c ON c.row_num = 1 AND c.user_id = a.id\nWHERE online_at >= datetime('now', '-1 minute')\nGROUP BY c.node;\n",
     "rawQueryText": "SELECT c.node,\n       COUNT(a.id) AS 'users'\nFROM users AS a\nLEFT JOIN (\n    SELECT\n        user_id,\n        case when n.name = '' then 'Main' else IFNULL(n.name, 'Main') end AS node,\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY a.ID) AS row_num\n    FROM node_user_usages AS a\n    LEFT JOIN nodes AS n ON n.id = a.node_id\n    WHERE DATE(a.created_at) = DATE('now')\n        AND strftime('%H', a.created_at) = strftime('%H', 'now')\n) AS c ON c.row_num = 1 AND c.user_id = a.id\nWHERE online_at >= datetime('now', '-1 minute')\nGROUP BY c.node;\n"
    }
   ]
  },
  {
   "title": "Connections by Client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT b.type AS 'Client',\n       COUNT(a.id) AS 'Users'\nFROM users AS a\nLEFT JOIN (\n    SELECT DISTINCT \n           sub_last_user_agent,\n           CASE \n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\n           END AS type\n    FROM users\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\nWHERE online_at >= datetime('now', '-1 minute')\nGROUP BY b.type;\n",
     "rawQueryText": "SELECT b.type AS 'Client',\n       COUNT(a.id) AS 'Users'\nFROM users AS a\nLEFT JOIN (\n    SELECT DISTINCT \n           sub_last_user_agent,\n           CASE \n               WHEN sub_last_user_agent IS NULL OR TRIM(sub_last_user_agent) = '' THEN 'Unknown'  \n               ELSE SUBSTR(sub_last_user_agent, 1, INSTR(sub_last_user_agent, '/')-1)\n           END AS type\n    FROM users\n) AS b ON b.sub_last_user_agent = a.sub_last_user_agent\nWHERE online_at >= datetime('now', '-1 minute')\nGROUP BY b.type;\n"
    }
   ]
  },
  {
   "title": "Online Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select \n  name\nfrom nodes where status in ('connected') ",
     "rawQueryText": "Select \n  name\nfrom nodes where status in ('connected') "
    }
   ]
  },
  {
   "title": "Offline Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select \n  name\nfrom nodes where status <> 'connected'",
     "rawQueryText": "Select \n  name\nfrom nodes where status <> 'connected'"
    }
   ]
  },
  {
   "title": "Today users",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "SELECT IFNULL(n.name, 'Main') AS node, SUM(a.used_traffic) AS used_traffic\n       \nFROM node_user_usages a\nLEFT JOIN users u ON u.id = a.user_id\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY IFNULL(n.name, 'Main');\n",
     "rawQueryText": "SELECT IFNULL(n.name, 'Main') AS node, SUM(a.used_traffic) AS used_traffic\n       \nFROM node_user_usages a\nLEFT JOIN users u ON u.id = a.user_id\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY IFNULL(n.name, 'Main');\n"
    }
   ]
  },
  {
   "title": "Traffic by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "SELECT IFNULL(n.name, 'Main') AS Node,\n       SUM(a.used_traffic) AS Traffic\nFROM node_user_usages a\nLEFT JOIN users u ON u.id = a.user_id\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY IFNULL(n.name, 'Main');\n",
     "rawQueryText": "SELECT IFNULL(n.name, 'Main') AS Node,\n       SUM(a.used_traffic) AS Traffic\nFROM node_user_usages a\nLEFT JOIN users u ON u.id = a.user_id\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY IFNULL(n.name, 'Main');\n"
    }
   ]
  },
  {
   "title": "Traffic by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "SELECT strftime('%s', a.created_at) AS 'Datetime', SUM(a.used_traffic) AS 'Traffic' \nFROM node_user_usages a\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY a.created_at\nORDER BY a.created_at ASC;\n",
     "rawQueryText": "SELECT strftime('%s', a.created_at) AS 'Datetime', SUM(a.used_traffic) AS 'Traffic' \nFROM node_user_usages a\nLEFT JOIN nodes n ON n.id = a.node_id\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY a.created_at\nORDER BY a.created_at ASC;\n",
     "timeColumns": [ "Datetime" ]
    }
   ]
  },
  {
   "title": "Connections by time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT strftime('%s', a.created_at) AS 'Datetime', COUNT(a.created_at) 'Users'\nFROM node_user_usages a\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY a.created_at\nORDER BY a.created_at ASC\n",
     "rawQueryText": "SELECT strftime('%s', a.created_at) AS 'Datetime', COUNT(a.created_at) 'Users'\nFROM node_user_usages a\nWHERE a.created_at >= datetime(DATE('now'), '00:00:00')\nGROUP BY a.created_at\nORDER BY a.created_at ASC\n",
     "timeColumns": [ "Datetime" ]
    }
   ]
  }
 ]
}